networks:
  eshop-on-web-net:
    external: true

services:
  basket-db:
    image: postgres:16
    container_name: basket-db
    environment:
      POSTGRES_USER: basketuser
      POSTGRES_PASSWORD: basketpass
      POSTGRES_DB: basketdb
    ports: ["5434:5432"]

  basket-api:
    container_name: basket-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - basket-db
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5004
      ConnectionStrings__Default: Host=basket-db;Port=5432;Database=basketdb;Username=basketuser;Password=basketpass
    ports: ["5004:5004"]
  
volumes:
  basket_data: