networks:
  eshop-on-web-net:
    external: true

volumes:
  basket_data:

services:
  basket-db:
    image: postgres:16
    container_name: basket-db
    environment:
      POSTGRES_USER: basketuser
      POSTGRES_PASSWORD: basketpass
      POSTGRES_DB: basketdb
    volumes:
      - basket_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"          
    networks:
      - eshop-on-web-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U basketuser -d basketdb" ]
      interval: 5s
      timeout: 3s
      retries: 20

  basket-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: basket-api
    depends_on:
      basket-db:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://0.0.0.0:5004
      ConnectionStrings__Default: Host=basket-db;Port=5432;Database=basketdb;Username=basketuser;Password=basketpass
    ports:
      - "5004:5004"
    networks:
      - eshop-on-web-net
    restart: unless-stopped
