networks:
  eshop-on-web-net:
    external: true
services:
  app:
    build: .
    container_name: storage-app
    depends_on:
      - db
      - rabbitmq
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: storage-db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: storage-db
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
    networks:
      - eshop-on-web-net

  db:
    image: postgres:16
    container_name: storage-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storage-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eshop-on-web-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: storage-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eshop-on-web-net

  pgadmin:  
    container_name: storage-pgadmin
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - eshop-on-web-net

volumes:
  postgres_data:
  pgadmin_data: