# MicroServices/ApiGatewayMicroService/docker-compose.yml
networks:
  eshop-on-web-net:
    external: true

services:
  gateway:
    build: .
    ports:
      - "8090:8080"            
    environment:
      ORDERS_BACKENDS:  http://order:8001
      CATALOG_BACKENDS: http://catalog-api:8000
    networks:
      eshop-on-web-net:
        aliases:
          - gateway           
    restart: unless-stopped
