services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5433:5432"  # host port 5433 maps to container 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - eshop-on-web-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - eshop-on-web-net

  order:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/orders
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - eshop-on-web-net
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload

  order-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - eshop-on-web-net

networks:
  eshop-on-web-net:
    external: true
