version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: orders
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  order:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:password@db:5432/orders
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
